# Alternative Docker Compose for Oracle Database 23c Free
# This is often easier to set up than Oracle XE
version: '3.8'

services:
  oracle-free:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-free-liquibase
    environment:
      # Set the Oracle root password
      ORACLE_PWD: OraclePassword123
      # Enable automatic database startup
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      # Map Oracle default port
      - "1521:1521"
      # Map Oracle Enterprise Manager Express port
      - "5500:5500"
    volumes:
      # Persist database data
      - oracle_free_data:/opt/oracle/oradata
      # Mount initialization scripts
      - ./docker/init-scripts:/opt/oracle/scripts/startup
    restart: unless-stopped
    shm_size: 2g
    # Resource limits for Oracle Free
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Database management tool
  adminer:
    image: adminer
    container_name: oracle-adminer-free
    ports:
      - "8080:8080"
    depends_on:
      - oracle-free
    restart: unless-stopped

volumes:
  oracle_free_data:
    driver: local
